//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomDevice
    {
        public string ClassroomID { get; set; }
        public int DeviceID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Classroom Classroom { get; set; }
    }
}
