//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classroom()
        {
            this.ClassroomDevices = new HashSet<ClassroomDevice>();
        }
    
        public string ClassroomID { get; set; }
        public string ClassroomName { get; set; }
        public string FLoorID { get; set; }
        public string ClassroomStatus { get; set; }
        public string ClassroomServerIPV4Address { get; set; }
        public Nullable<int> ClassroomPortNumber { get; set; }
    
        public virtual FloorOfArea FloorOfArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassroomDevice> ClassroomDevices { get; set; }
    }
}
